### PR TITLE
Responsive css

### PR DESCRIPTION
**Pull request by KANAjetzt**
*Relevant PR's*
#1 #2 

*Addresses [this comment](https://github.com/BrotatoMods/Brotato-Item-Creator-WebApp/pull/2#issuecomment-1417506432) from #2*

---

I hope I addressed most of your feedback from the last PR.
I use grid and removed some of the hard coded widths because it make the layout just a bit more fluent.

I think this time the general style is preserved 😃

### CODE REVIEW

**Comment by ithinkandicode** [comment]
This is a step in the right direction, but it needs some attention at various viewports, eg:

viewport-small-desktop

Ideally we want the experience on smaller viewports to be as close to desktop as possible, so that going below the current full-width viewport feels seamless.

There's also an issue where the main container is now vertically centered. I did this originally too, but found that it causes issues as you add new lines. To replicate, press the "Positive" button 6 times. After the 4th/5th time, the page will move position, so you need to change your cursor position to press it again; so you do that, then the page moves again, etc. The issue persists until the main container has moved up far enough that there's no space between main and the header, which stops the issue from happening. On PRD atm, `main` is already right below the header, so the issue doesn't occur, which means the user experience isn't disrupted in this regard.

I've published this PR on a test URL so you can try this yourself immediately:

- PRD: [item-creator-prd](https://brotato.codemuffin.com/item-creator-prd/)
- PR4: [item-creator-pr](https://brotato.codemuffin.com/item-creator-pr/) 

FYI I've also edited the original description to link to the quoted text instead of quoting it directly, to keep the description short and to the point :)

**Comment by KANAjetzt** [comment]
> To replicate, press the "Positive" button 6 times.

Ohhh okay I see 

> Ideally we want the experience on smaller viewports to be as close to desktop as possible, so that going below the current full-width viewport feels seamless.

Hmm yes some breaks are a bit awkward. I think:

- 4 columns
- 2 columns
- 1 column

will look better.

Not sure how to handle the gaps between the panels on the 2 column layout.

I will try some stuff and will be back with an update 😃

**Comment by ithinkandicode** [comment]
@KANAjetzt FYI I'm overhauling the layout and will probably bake responsiveness into it

**Comment by KANAjetzt** [comment]
Alright - sounds good 👍

**Pull request closed without merging**
